create extension if not exists vector;

create table device (
    id varchar(64) primary key,
    serial_number varchar(128) not null unique,
    model varchar(128) not null,
    current_version varchar(64) not null,
    online boolean not null,
    storage_available_mb integer not null,
    simulated boolean not null default true,
    created_at timestamptz not null
);

create table firmware_version (
    id varchar(64) primary key,
    version varchar(64) not null,
    release_status varchar(32) not null,
    compatible_models text not null,
    checksum varchar(128) not null,
    released_at timestamptz not null,
    simulated boolean not null default true,
    unique (version, checksum)
);

create table upgrade_task (
    id uuid primary key,
    device_id varchar(64) not null references device(id),
    target_firmware_version_id varchar(64) not null references firmware_version(id),
    status varchar(32) not null,
    failure_code varchar(64) not null,
    failure_summary varchar(512) not null,
    failed_at timestamptz not null,
    version bigint not null default 0,
    simulated boolean not null default true
);

create index idx_upgrade_task_status_failed_at on upgrade_task(status, failed_at desc);

create table failure_log (
    id bigint generated by default as identity primary key,
    upgrade_task_id uuid not null references upgrade_task(id),
    observed_at timestamptz not null,
    level varchar(16) not null,
    code varchar(64) not null,
    message varchar(1000) not null,
    source varchar(128) not null,
    simulated boolean not null default true
);

create index idx_failure_log_task_observed_at on failure_log(upgrade_task_id, observed_at desc);

create table message_state (
    id bigint generated by default as identity primary key,
    upgrade_task_id uuid not null references upgrade_task(id),
    message_type varchar(64) not null,
    send_status varchar(32) not null,
    callback_status varchar(32) not null,
    observed_at timestamptz not null,
    detail varchar(1000) not null,
    simulated boolean not null default true
);

create index idx_message_state_task_observed_at on message_state(upgrade_task_id, observed_at desc);

create table operator_user (
    username varchar(128) primary key,
    password_hash varchar(255) not null,
    role varchar(64) not null,
    enabled boolean not null,
    created_at timestamptz not null
);

create table diagnostic_task (
    id uuid primary key,
    upgrade_task_id uuid not null references upgrade_task(id),
    state varchar(32) not null,
    version bigint not null default 0,
    created_at timestamptz not null,
    updated_at timestamptz not null
);

create unique index uq_diagnostic_task_active_upgrade_task
    on diagnostic_task(upgrade_task_id)
    where state not in ('COMPLETED', 'INCOMPLETE');

create table diagnostic_report (
    id uuid primary key,
    diagnostic_task_id uuid not null unique references diagnostic_task(id),
    report jsonb not null,
    created_at timestamptz not null
);

create table retry_plan (
    id uuid primary key,
    diagnostic_task_id uuid not null references diagnostic_task(id),
    plan_version integer not null,
    status varchar(32) not null,
    expires_at timestamptz not null,
    snapshot jsonb not null,
    created_at timestamptz not null,
    unique (diagnostic_task_id, plan_version)
);

create table retry_execution (
    id uuid primary key,
    retry_plan_id uuid not null unique references retry_plan(id),
    idempotency_key varchar(255) not null unique,
    status varchar(32) not null,
    result jsonb,
    created_at timestamptz not null,
    updated_at timestamptz not null
);

create table knowledge_document (
    id varchar(128) primary key,
    document_version varchar(64) not null,
    document_type varchar(64) not null,
    status varchar(32) not null,
    applicable_components text not null,
    updated_at timestamptz not null,
    content text not null,
    content_hash varchar(128) not null unique,
    embedding vector(384)
);

create table audit_event (
    id uuid primary key,
    occurred_at timestamptz not null,
    actor varchar(128) not null,
    object_type varchar(64) not null,
    object_id varchar(128) not null,
    action varchar(64) not null,
    result varchar(64) not null,
    correlation_id varchar(128),
    summary varchar(1000) not null,
    metadata jsonb
);

create index idx_audit_event_object_time on audit_event(object_type, object_id, occurred_at);
